# Generated by Django 3.2.8 on 2022-08-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatos',
            old_name='public',
            new_name='_public',
        ),
        migrations.RenameField(
            model_name='metadatos',
            old_name='secret',
            new_name='_secret',
        ),
    ]
