# Generated by Django 3.2.8 on 2022-08-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220803_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadatos',
            old_name='_public',
            new_name='public_key',
        ),
        migrations.RenameField(
            model_name='metadatos',
            old_name='_secret',
            new_name='secret_key',
        ),
    ]
